## Python Mini-Project: Data Clean-Up, Pt. 2

Pay close attention to the prompts to help guide you through this task.

In [1]:
# Dependencies
import pandas as pd

import numpy as np

pd.set_option('display.max_columns', None)

In [2]:
# load CSV

Mini_Project_2 = "Resources/2016-FCC-New-Coders-Survey-Data.csv"

In [3]:
# Read with pandas--low_memory required to suppress errors about mixed data types
# You may need to encode this file

encoders_pd = pd.read_csv('Resources/2016-FCC-New-Coders-Survey-Data.csv',encoding='utf-8')

encoders_pd.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (21,57) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampMonthsAgo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CodeEventCoffee,CodeEventConferences,CodeEventDjangoGirls,CodeEventGameJam,CodeEventGirlDev,CodeEventHackathons,CodeEventMeetup,CodeEventNodeSchool,CodeEventNone,CodeEventOther,CodeEventRailsBridge,CodeEventRailsGirls,CodeEventStartUpWknd,CodeEventWomenCode,CodeEventWorkshop,CommuteTime,CountryCitizen,CountryLive,EmploymentField,EmploymentFieldOther,EmploymentStatus,EmploymentStatusOther,ExpectedEarning,FinanciallySupporting,Gender,HasChildren,HasDebt,HasFinancialDependents,HasHighSpdInternet,HasHomeMortgage,HasServedInMilitary,HasStudentDebt,HomeMortgageOwe,HoursLearning,ID.x,ID.y,Income,IsEthnicMinority,IsReceiveDiabilitiesBenefits,IsSoftwareDev,IsUnderEmployed,JobApplyWhen,JobPref,JobRelocateYesNo,JobRoleInterest,JobRoleInterestOther,JobWherePref,LanguageAtHome,MaritalStatus,MoneyForLearning,MonthsProgramming,NetworkID,Part1EndTime,Part1StartTime,Part2EndTime,Part2StartTime,PodcastChangeLog,PodcastCodeNewbie,PodcastCodingBlocks,PodcastDeveloperTea,PodcastDotNetRocks,PodcastHanselminutes,PodcastJSJabber,PodcastJsAir,PodcastNone,PodcastOther,PodcastProgrammingThrowDown,PodcastRubyRogues,PodcastSEDaily,PodcastShopTalk,PodcastTalkPython,PodcastWebAhead,ResourceBlogs,ResourceBooks,ResourceCodeWars,ResourceCodecademy,ResourceCoursera,ResourceDevTips,ResourceEdX,ResourceEggHead,ResourceFCC,ResourceGoogle,ResourceHackerRank,ResourceKhanAcademy,ResourceLynda,ResourceMDN,ResourceOdinProj,ResourceOther,ResourcePluralSight,ResourceReddit,ResourceSkillCrush,ResourceSoloLearn,ResourceStackOverflow,ResourceTreehouse,ResourceUdacity,ResourceUdemy,ResourceW3Schools,ResourceYouTube,SchoolDegree,SchoolMajor,StudentDebtOwe
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,United States of America,United States of America,office and administrative support,NaN,Employed for wages,NaN,NaN,0.0,male,0.0,1.0,1.0,1.0,0.0,0.0,1.0,NaN,30.0,cef35615d61b202f1dc794ef2746df14,48fd66e15301df9727e13e6e80aef941,32000.0,0.0,0.0,0.0,1.0,NaN,freelance,NaN,NaN,NaN,NaN,English,married or domestic partnership,0.0,1.0,2c6f0af42c,2016-03-29 21:24:53,2016-03-29 21:23:13,2016-03-29 21:27:25,2016-03-29 21:24:57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,20000.0
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,United States of America,United States of America,food and beverage,NaN,Employed for wages,NaN,50000.0,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,30.0,323e5a113644d18185c743c241407754,a8cd67193184084b1e32b362225bf280,15000.0,0.0,0.0,0.0,1.0,Within the next 6 months,work for a startup,1.0,Front-End Web Developer,NaN,in an office with other developers,English,NaN,20.0,2.0,d048ac774d,2016-03-29 21:27:09,2016-03-29 21:24:59,2016-03-29 21:29:10,2016-03-29 21:27:14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Front-end happy hour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,"some college credit, no degree",NaN,NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,United States of America,United States of America,finance,NaN,Employed for wages,NaN,NaN,NaN,male,NaN,0.0,0.0,1.0,NaN,0.0,NaN,NaN,20.0,b29a1027e5cd062e654a63764157461d,129b4479808fe006e768502b957a0c52,48000.0,0.0,0.0,0.0,0.0,NaN,start your own business,NaN,NaN,NaN,NaN,English,NaN,50.0,24.0,241513bbbe,2016-03-29 21:27:11,2016-03-29 21:25:37,2016-03-29 21:28:21,2016-03-29 21:27:13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,high school diploma or equivalent (GED),NaN,NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,45.0,United States of America,United States of America,"arts, entertainment, sports, or media",NaN,Employed for wages,NaN,65000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,20.0,04a11e4bcb573a1261eb0d9948d32637,7313b696ac8f0517a3d0ec7725039bb2,43000.0,0.0,0.0,0.0,1.0,Within the next 6 months,work for a startup,NaN,Front-End Web Developer,NaN,from home,English,NaN,100.0,3.0,809298e033,2016-03-29 21:28:47,2016-03-29 21:21:37,2016-03-29 21:30:51,2016-03-29 21:28:51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bachelor's degree,Cinematography And Film,7000.0
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,United States of America,United States of America,education,NaN,Employed for wages,NaN,45000.0,NaN,female,NaN,1.0,0.0,1.0,0.0,0.0,0.0,NaN,25.0,9368291c93d5d5f5c8cdb1a575e18bec,d0f75544984896ccfd361af6d9b26047,6000.0,1.0,0.0,0.0,1.0,Within the next 6 months,work for a medium-sized company,1.0,Full-Stack Web Developer,NaN,in an office with other developers,Khmer,NaN,1300.0,48.0,cdc466b1ee,2016-03-29 21:29:27,2016-03-29 21:26:22,2016-03-29 21:31:54,2016-03-29 21:29:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"some college credit, no degree",NaN,NaN

In [4]:
# Take only columns 0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111
# Consider using iloc


encoders_pd = encoders_pd.iloc [: ,[0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 29, 30, 32, 36, 37, 45, 48, 56, 110, 111]]

encoders_pd.head()

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,office and administrative support,Employed for wages,male,0.0,30.0,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,food and beverage,Employed for wages,male,NaN,30.0,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Employed for wages,male,NaN,20.0,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20.0,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,education,Employed for wages,female,NaN,25.0,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN

In [5]:
# Change reading 0 and 1 to No and Yes, respectively

encoders_pd  = encoders_pd.replace([0, 1,], ["No","Yes"])

encoders_pd

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
0,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,office and administrative support,Employed for wages,male,No,30,32000.0,NaN,"some college credit, no degree",NaN
1,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,food and beverage,Employed for wages,male,NaN,30,15000.0,Front-End Web Developer,"some college credit, no degree",NaN
2,19.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Employed for wages,male,NaN,20,48000.0,NaN,high school diploma or equivalent (GED),NaN
3,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,NaN,20,43000.0,Front-End Web Developer,bachelor's degree,Cinematography And Film
4,20.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,education,Employed for wages,female,NaN,25,6000.0,Full-Stack Web Developer,"some college credit, no degree",NaN
5,34.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,finance,Self-employed freelancer,male,NaN,5,40000.0,NaN,bachelor's degree,English
6,23.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Singapore,software development,Employed for wages,male,NaN,8,32000.0,NaN,bachelor's degree,Computer Science
7,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United Kingdom,office and administrative support,Employed for wages,male,No,NaN,40000.0,NaN,master's degree (non-professional),Education
8,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5,80000.0,NaN,bachelor's degree,Business Administration
9,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,NaN,Employed for wages,male,NaN,20,80000.0,NaN,master's degree (non-professional),Business Administration
10,57.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,United States of America,NaN,Self-employed business owner,male,No,8,20000.0,NaN,bachelor's degree,Computer Science
11,23.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Bangladesh,NaN,Not working and not looking for work,male,NaN,5,NaN,NaN,"some college credit, no degree",NaN
12,47.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Canada,health care,Employed for wages,male,NaN,5,90000.0,NaN,bachelor's degree,Mechanical Engineering
13,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5,NaN,NaN,bachelor's degree,Business Administration
14,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"between 100,000 and 1 million",NaN,Bosnia & Herzegovina,sales,Self-employed business owner,male,Yes,2,NaN,NaN,"some college credit, no degree",NaN
15,31.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Russia,software development,Employed for wages,female,NaN,10,NaN,NaN,"professional degree (MBA, MD, JD, etc.)",Math
16,27.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,software development,Employed for wages,female,NaN,4,80000.0,NaN,bachelor's degree,Economics
17,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,United States of America,education,Employed for wages,male,NaN,5,17000.0,NaN,bachelor's degree,Music
18,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Canada,software development,Self-employed freelancer,male,NaN,2,16000.0,NaN,bachelor's degree,Music
19,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,Croatia,NaN,Not working but looking for work,male,No,20,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
20,32.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,more than 1 million,NaN,United States of America,NaN,Employed for wages,female,Yes,5,200000.0,Full-Stack Web Developer,master's degree (non-professional),Geology
21,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Doing an unpaid internship,female,NaN,NaN,NaN,NaN,bachelor's degree,Computer Science
22,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,No,10,100000.0,NaN,bachelor's degree,Computer Science
23,44.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,office and administrative support,Employed for wages,female,No,30,41000.0,NaN,bachelor's degree,Political Science
24,21.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,NaN,Not working but looking for work,male,NaN,25,NaN,NaN,bachelor's degree,Computer Science
25,21.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working but looking for work,male,NaN,25,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
26,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,South Africa,NaN,Self-employed freelancer,male,No,Yes,12000.0,NaN,high school diploma or equivalent (GED),NaN
27,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,United States of America,software development,Employed for wages,male,Yes,10,60000.0,NaN,"trade, technical, or vocational training",NaN
28,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,10,75000.0,Full-Stack Web Developer,bachelor's degree,Political Science
29,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"less than 100,000",NaN,United Kingdom,software development,Employed for wages,male,Yes,5,35000.0,NaN,master's degree (non-professional),Physics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15590,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,NaN,2,200000.0,NaN,bachelor's degree,Computer Science
15591,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Brazil,software development and IT,Employed for wages,male,No,2,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Computer Systems Networking and Telecommunicat...
15592,43.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,Yes,3,200000.0,NaN,high school diploma or equivalent (GED),NaN
15593,29.0,Yes,No,NaN,No,Camp Code Away,NaN,No,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,female,No,5,200000.0,NaN,bachelor's degree,Accounting
15594,36.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,United States of America,finance,Employed for wages,male,Yes,Yes,200000.0,NaN,bachelor's degree,Engineering
15595,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Ukraine,software development and IT,Self-employed freelancer,male,No,30,200000.0,NaN,some high school,NaN
15596,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,"less than 100,000",NaN,Brazil,software development and IT,Employed for wages,male,Yes,2,200000.0,NaN,high school diploma or equivalent (GED),NaN
15597,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Ukraine,legal,Self-employed freelancer,male,NaN,6,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Law
15598,28.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,"less than 100,000",NaN,United States of America,food and beverage,Employed for wages,male,Yes,20,200000.0,Full-Stack Web Developer,associate's degree,Computer and Information Systems Security
15599,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,NaN,5,200000.0,NaN,"some college credit, no degree",NaN
15600,28.0,Yes,Yes,Yes,No,Epicodus,36000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,female,NaN,8,200000.0,NaN,bachelor's degree,Marketing
15601,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,legal,Employed for wages,male,NaN,10,200000.0,NaN,bachelor's degree,Criminal Justice and Safety Studies
15602,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,India,software development and IT,Employed for wages,male,NaN,50,200000.0,Data Scientist / Data Engineer,bachelor's degree,Mathematics
15603,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,software development and IT,Employed for wages,male,NaN,4,200000.0,NaN,bachelor's degree,Computer Science
15604,35.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"less than 100,000",NaN,Norway,construction and extraction,Employed for wages,male,NaN,5,200000.0,Front-End Web Developer,"some college credit, no degree",NaN
15605,31.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Portugal,software development and IT,Employed for wages,male,NaN,5,200000.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15606,43.0,No,NaN,NaN,NaN,NaN,NaN,NaN,3,more than 1 million,NaN,Canada,legal,Self-employed business owner,male,Yes,3,200000.0,NaN,bachelor's degree,Physics
15607,25.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Philippines,software development,Self-employed freelancer,male,No,8,200000.0,NaN,no high school (secondary school),NaN
15608,43.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,United States of America,health care,Employed for wages,male,Yes,6,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical Engineering
15609,33.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Mexico,software development and IT,Employed for wages,male,No,16,200000.0,NaN,bachelor's degree,Software Engineering
15610,29.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,education,Employed for wages,male,NaN,5,200000.0,Front-End Web Developer,master's degree (non-professional),Religious Studies
15611,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,Yes,more than 1 million,NaN,Canada,software development and IT,Self-employed business owner,male,Yes,40,200000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Electrical and Electronics Engineering
15612,45.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Employed for wages,female,NaN,2,200000.0,NaN,"some college credit, no degree",NaN
15613,30.0,No,NaN,NaN,NaN,NaN,NaN,NaN,2,more than 1 million,NaN,South Africa,software development and IT,Employed for wages,male,Yes,4,200000.0,NaN,"trade, technical, or vocational training",NaN
15614,47.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"between 100,000 and 1 million",NaN,United States of America,finance,Employed for wages,male,NaN,3,26000.0,NaN,"trade, technical, or vocational training",NaN
15615,39.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Kenya,software development and IT,Self-employed freelancer,male,No,40,10000.0,NaN,bachelor's degree,Chemistry
15616,27.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,No,15,10000.0,Front-End Web Developer,bachelor's degree,Electrical Engineering
15617,37.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Nigeria,NaN,Self-employed freelancer,male,NaN,14,48000.0,NaN,bachelor's degree,Chemistry
15618,26.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,Spain,education,Self-employed freelancer,male,NaN,10,10000.0,NaN,master's degree (non-professional),Math
15619,22.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,more than 1 million,NaN,United States of America,"arts, entertainment, sports, or media",Employed for wages,female,No,2,18000.0,NaN,bachelor's degree,Graphic Design

In [6]:
# Extract rows for only those who attended a bootcamp


AttendedBootcamp_pd = encoders_pd.loc[encoders_pd['AttendedBootcamp']== "Yes" ]

AttendedBootcamp_pd

,Age,AttendedBootcamp,BootcampFinish,BootcampFullJobAfter,BootcampLoanYesNo,BootcampName,BootcampPostSalary,BootcampRecommend,ChildrenNumber,CityPopulation,CodeEventBootcamp,CountryLive,EmploymentField,EmploymentStatus,Gender,HasChildren,HoursLearning,Income,JobRoleInterest,SchoolDegree,SchoolMajor
93,32.0,Yes,Yes,No,No,Codify Academy,NaN,No,NaN,"between 100,000 and 1 million",NaN,United States of America,"arts, entertainment, sports, or media",Self-employed business owner,male,NaN,20,67000.0,NaN,bachelor's degree,Biology
97,26.0,Yes,Yes,Yes,No,DaVinci Coders,45000.0,No,NaN,more than 1 million,NaN,United States of America,software development,Employed for wages,male,No,10,40000.0,NaN,master's degree (non-professional),Music
130,41.0,Yes,Yes,Yes,Yes,Coder Foundry,75000.0,Yes,3,"less than 100,000",NaN,United States of America,software development,Employed for wages,male,Yes,30,75000.0,NaN,"some college credit, no degree",NaN
159,26.0,Yes,Yes,No,No,General Assembly,NaN,No,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working and not looking for work,female,NaN,30,NaN,Full-Stack Web Developer,"some college credit, no degree",NaN
188,24.0,Yes,No,NaN,Yes,NaN,NaN,No,NaN,"between 100,000 and 1 million",NaN,Canada,NaN,Not working but looking for work,female,NaN,60,NaN,NaN,"some college credit, no degree",NaN
206,36.0,Yes,Yes,No,No,Thinkful,NaN,No,2,more than 1 million,NaN,Japan,NaN,A stay-at-home parent or homemaker,female,Yes,20,NaN,Mobile Developer,bachelor's degree,Communications
209,25.0,Yes,Yes,No,Yes,Flatiron School,NaN,Yes,NaN,more than 1 million,NaN,Mexico,NaN,Not working but looking for work,male,NaN,40,NaN,Full-Stack Web Developer,"professional degree (MBA, MD, JD, etc.)",Computer Science
236,52.0,Yes,Yes,Yes,No,General Assembly,45000.0,No,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Self-employed freelancer,male,NaN,30,45000.0,NaN,"some college credit, no degree",NaN
272,38.0,Yes,Yes,Yes,Yes,DevMountain,50000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,5,NaN,NaN,bachelor's degree,Structural Engineering
273,35.0,Yes,Yes,Yes,Yes,The Iron Yard,60000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Employed for wages,male,NaN,10,54000.0,NaN,bachelor's degree,Public Administration
285,23.0,Yes,Yes,Yes,No,Codeup,40000.0,Yes,NaN,NaN,NaN,United States of America,software development,Employed for wages,male,NaN,40,NaN,NaN,bachelor's degree,Journalism
315,31.0,Yes,Yes,No,No,General Assembly,NaN,No,NaN,"between 100,000 and 1 million",NaN,United States of America,software development,Self-employed freelancer,genderqueer,NaN,20,35000.0,User Experience Designer,bachelor's degree,Communications
316,22.0,Yes,Yes,No,No,Code Fellows,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working but looking for work,male,NaN,30,NaN,Front-End Web Developer,associate's degree,General Studies
328,30.0,Yes,No,NaN,No,Bloc.io,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,sales,Employed for wages,female,NaN,20,35000.0,Front-End Web Developer,bachelor's degree,Advertising and Marketing
426,30.0,Yes,Yes,No,Yes,General Assembly,NaN,Yes,NaN,"less than 100,000",NaN,United States of America,education,Employed for wages,male,NaN,40,NaN,Full-Stack Web Developer,bachelor's degree,Liberal Arts
435,26.0,Yes,Yes,No,Yes,The Firehose Project,NaN,Yes,NaN,more than 1 million,NaN,United States of America,NaN,Not working but looking for work,male,NaN,50,NaN,Front-End Web Developer,associate's degree,Psychology
449,38.0,Yes,Yes,No,No,General Assembly,NaN,Yes,NaN,more than 1 million,NaN,United States of America,NaN,Not working but looking for work,female,NaN,20,NaN,NaN,bachelor's degree,Architecture
465,40.0,Yes,No,NaN,Yes,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,A stay-at-home parent or homemaker,female,NaN,8,NaN,Quality Assurance Engineer,master's degree (non-professional),English
470,45.0,Yes,No,NaN,No,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working and not looking for work,female,NaN,50,NaN,Mobile Developer,bachelor's degree,Liberal Arts
478,37.0,Yes,No,NaN,Yes,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,NaN,female,NaN,50,NaN,Full-Stack Web Developer,bachelor's degree,Sociology
481,27.0,Yes,Yes,No,No,Prime Digital Academy,NaN,Yes,NaN,"less than 100,000",NaN,United States of America,NaN,Not working but looking for work,female,NaN,2,NaN,Front-End Web Developer,"trade, technical, or vocational training",NaN
488,25.0,Yes,No,NaN,Yes,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Unable to work,male,NaN,9,NaN,Front-End Web Developer,bachelor's degree,Psychology
505,28.0,Yes,Yes,Yes,Yes,Free Code Camp is not a bootcamp - please scro...,50000.0,Yes,Yes,more than 1 million,NaN,United States of America,software development and IT,Employed for wages,male,Yes,15,38000.0,NaN,"some college credit, no degree",NaN
506,38.0,Yes,Yes,No,No,Prime Digital Academy,NaN,Yes,2,more than 1 million,NaN,United States of America,NaN,Not working but looking for work,female,Yes,25,NaN,Back-End Web Developer,bachelor's degree,Anthropology
510,33.0,Yes,No,NaN,No,Flatiron School,NaN,Yes,NaN,more than 1 million,NaN,Australia,NaN,Not working and not looking for work,male,NaN,60,NaN,Full-Stack Web Developer,"trade, technical, or vocational training",NaN
522,33.0,Yes,Yes,No,Yes,Galvanize,NaN,No,NaN,"less than 100,000",NaN,United States of America,NaN,Employed for wages,male,NaN,10,NaN,Full-Stack Web Developer,bachelor's degree,Psychology
525,31.0,Yes,No,NaN,No,Ada,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working and not looking for work,female,NaN,50,NaN,Full-Stack Web Developer,bachelor's degree,Psychology
526,30.0,Yes,No,NaN,No,Prime Digital Academy,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,NaN,Not working but looking for work,female,NaN,50,NaN,Back-End Web Developer,bachelor's degree,Nutrition
533,20.0,Yes,No,NaN,No,NaN,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,India,software development and IT,Employed for wages,male,NaN,6,6000.0,NaN,bachelor's degree,Communications
543,27.0,Yes,Yes,Yes,No,Skillcrush,58000.0,Yes,NaN,"less than 100,000",NaN,United States of America,software development and IT,Employed for wages,female,NaN,5,43000.0,NaN,bachelor's degree,Business Administration
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14653,29.0,Yes,Yes,Yes,No,Epicodus,50000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,female,NaN,5,15600.0,NaN,bachelor's degree,Political Science
14681,24.0,Yes,Yes,No,No,Dev Bootcamp,NaN,Yes,NaN,more than 1 million,NaN,Ukraine,software development and IT,Self-employed freelancer,male,No,4,60000.0,NaN,bachelor's degree,Computer Science
14695,22.0,Yes,No,NaN,No,AcadGild,NaN,Yes,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,No,90,24000.0,NaN,bachelor's degree,Computer Science
14701,23.0,Yes,No,NaN,Yes,Devschool,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,Romania,finance,Employed for wages,male,NaN,8,60000.0,Mobile Developer,some high school,NaN
14751,29.0,Yes,Yes,Yes,No,Orange County Code School,90000.0,No,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,No,20,48000.0,NaN,bachelor's degree,Industrial Engineering
14766,25.0,Yes,Yes,No,No,DaVinci Coders,NaN,No,NaN,"less than 100,000",NaN,United States of America,software development and IT,Self-employed business owner,male,NaN,50,48000.0,Full-Stack Web Developer,"trade, technical, or vocational training",NaN
14797,37.0,Yes,No,NaN,No,NaN,NaN,Yes,3,more than 1 million,NaN,Malaysia,software development and IT,Self-employed freelancer,male,Yes,20,28800.0,NaN,bachelor's degree,Electrical Engineering
14846,15.0,Yes,No,NaN,No,Free Code Camp is not a bootcamp - please scro...,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,education,Employed for wages,female,NaN,10,8400.0,Back-End Web Developer,some high school,NaN
14987,NaN,Yes,No,NaN,No,LAMP Camp,NaN,Yes,NaN,"less than 100,000",NaN,United States of America,office and administrative support,Employed for wages,female,NaN,40,60000.0,NaN,associate's degree,Computer Networking
14992,24.0,Yes,No,NaN,No,Flatiron School,NaN,Yes,NaN,more than 1 million,NaN,Nigeria,software development and IT,Employed for wages,male,No,10,51432.0,NaN,associate's degree,Software Engineering
15062,29.0,Yes,No,NaN,Yes,New York Code + Design Academy,NaN,Yes,NaN,more than 1 million,NaN,United States of America,NaN,Employed for wages,genderqueer,NaN,20,36000.0,DevOps / SysAdmin,"trade, technical, or vocational training",NaN
15106,24.0,Yes,Yes,Yes,No,Prime Digital Academy,50000.0,Yes,NaN,NaN,NaN,United States of America,software development and IT,Employed for wages,female,NaN,10,48000.0,NaN,"some college credit, no degree",NaN
15128,24.0,Yes,Yes,No,Yes,IronHack,NaN,Yes,NaN,more than 1 million,NaN,United States of America,software development and IT,Employed for wages,female,No,30,18000.0,Full-Stack Web Developer,associate's degree,Computer Science
15165,26.0,Yes,No,NaN,No,Bloc.io,NaN,Yes,NaN,"less than 100,000",NaN,United States of America,"arts, entertainment, sports, or media",Self-employed freelancer,male,NaN,40,48000.0,Full-Stack Web Developer,master's degree (non-professional),Music Performance
15188,29.0,Yes,No,NaN,No,Free Code Camp is not a bootcamp - please scro...,NaN,Yes,NaN,more than 1 million,NaN,Philippines,software development and IT,Employed for wages,female,No,25,28560.0,NaN,bachelor's degree,Engineering
15239,28.0,Yes,Yes,Yes,No,Prime Digital Academy,65000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,NaN,45,48000.0,NaN,bachelor's degree,Neuroscience
15348,24.0,Yes,No,NaN,No,CodeNinja,NaN,Yes,NaN,more than 1 million,NaN,Vietnam,software development and IT,Self-employed freelancer,male,NaN,30,12000.0,NaN,high school diploma or equivalent (GED),NaN
15395,31.0,Yes,NaN,NaN,NaN,NaN,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,Puerto Rico,legal,Employed for wages,female,NaN,6,60000.0,NaN,"some college credit, no degree",NaN
15400,32.0,Yes,No,NaN,No,Fire Bootcamp,NaN,No,NaN,more than 1 million,NaN,Saudi Arabia,software development and IT,Self-employed freelancer,female,NaN,12,24000.0,NaN,"professional degree (MBA, MD, JD, etc.)",Computer Systems Networking and Telecommunicat...
15406,23.0,Yes,Yes,Yes,No,App Academy,79000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,male,NaN,No,12000.0,NaN,bachelor's degree,History
15412,24.0,Yes,Yes,No,Yes,New York Code + Design Academy,NaN,Yes,NaN,"less than 100,000",NaN,United States of America,software development and IT,Self-employed freelancer,male,NaN,10,36000.0,Full-Stack Web Developer,bachelor's degree,English
15420,25.0,Yes,Yes,Yes,No,We Can Code IT,10000.0,No,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,male,No,NaN,12000.0,NaN,bachelor's degree,Information Technology
15421,22.0,Yes,Yes,No,No,NaN,NaN,Yes,NaN,more than 1 million,NaN,Nigeria,software development and IT,Self-employed freelancer,male,NaN,30,7200.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15436,45.0,Yes,No,NaN,No,Starter League,NaN,Yes,Yes,"between 100,000 and 1 million",NaN,Ukraine,construction and extraction,Self-employed freelancer,male,Yes,5,36000.0,Full-Stack Web Developer,high school diploma or equivalent (GED),NaN
15465,25.0,Yes,No,NaN,No,CodeaCamp,NaN,Yes,NaN,"between 100,000 and 1 million",NaN,Ukraine,architecture or physical engineering,Employed for wages,male,NaN,15,14400.0,Back-End Web Developer,master's degree (non-professional),Electrical and Electronics Engineering
15539,39.0,Yes,Yes,Yes,Yes,CodeaCamp,NaN,Yes,NaN,more than 1 million,NaN,Mexico,NaN,Self-employed freelancer,female,NaN,15,36000.0,Full-Stack Web Developer,"some college credit, no degree",NaN
15540,24.0,Yes,Yes,Yes,Yes,Anyone Can Learn To Code,NaN,No,NaN,more than 1 million,NaN,Kenya,"arts, entertainment, sports, or media",Employed for wages,female,NaN,10,16800.0,NaN,bachelor's degree,Computer Systems Networking and Telecommunicat...
15541,23.0,Yes,Yes,Yes,No,CodeaCamp,21600.0,Yes,NaN,more than 1 million,NaN,Mexico,software development and IT,Employed for wages,male,NaN,24,42000.0,NaN,master's degree (non-professional),Computer Software Engineering
15593,29.0,Yes,No,NaN,No,Camp Code Away,NaN,No,NaN,more than 1 million,NaN,India,software development and IT,Employed for wages,female,No,5,200000.0,NaN,bachelor's degree,Accounting
15600,28.0,Yes,Yes,Yes,No,Epicodus,36000.0,Yes,NaN,"between 100,000 and 1 million",NaN,United States of America,software development and IT,Employed for wages,female,NaN,8,200000.0,NaN,bachelor's degree,Marketing

In [24]:
# Create DataFrame of the various boot camps along with the number of participants (enrollees)
# Create a DataFrame from using value_counts

number_of_participants_pd = pd.DataFrame( AttendedBootcamp_pd["BootcampName"].value_counts())

number_of_participants_pd = number_of_participants_pd.reset_index()

number_of_participants_pd.columns = ["BootcampName", "counts"]

number_of_participants_pd

                                          BootcampName  counts
0                                     General Assembly      90
1                                      Flatiron School      54
2                                         Dev Bootcamp      48
3                                        The Iron Yard      40
4                                Prime Digital Academy      30
5                                         Hack Reactor      29
6                                               Turing      27
7                                          App Academy      22
8                                   Hackbright Academy      22
9                                              Bloc.io      21
10                                        Code Fellows      21
11                      New York Code + Design Academy      20
12                                           Galvanize      20
13                                         MakerSquare      20
14                                         Coding Dojo      18
15                                The Firehose Project      16
16   Free Code Camp is not a bootcamp - please scro...      15
17                                            Epicodus      14
18                                         Dev Academy      13
19                                      Makers Academy      12
20                                   Tech Talent South      12
21                                         Coder Camps      11
22                                              Codeup      10
23                                      Launch Academy      10
24                                         DevMountain      10
25                                  Viking Code School      10
26                                      Software Guild      10
27                                                 Ada       9
28                                      4Geeks Academy       8
29                                           CodeaCamp       8
..                                                 ...     ...
98                                          Code Union       1
99                                            Alphappl       1
100                                  Data Science Dojo       1
101                                  World Tech Makers       1
102                                 The Data Incubator       1
103                               Ladies Learning Code       1
104                                              codeU       1
105                                  Astro Code School       1
106      Microsoft Research Data Science Summer School       1
107                                     Base10 Academy       1
108           Launch School (formerly Tealeaf Academy)       1
109                                  Ruby On The Beach       1
110                                      Coder Foundry       1
111                                  Founders & Coders       1
112                                       Byte Academy       1
113                                          Academy X       1
114                                         Stackademy       1
115                                Montana Code School       1
116                                    Operation Spark       1
117                                   CodeCraft School       1
118                                            Code 42       1
119                                CodeMasters Academy       1
120                                     Code Institute       1
121                              Austin Coding Academy       1
122                                           Le Wagon       1
123                                        DESIGNATION       1
124                                       Atlanta Code       1
125                              Academic Work Academy       1
126                                          SeedPaths       1
127                                        Coder's Lab       1

[128 rows x 2 columns]

In [25]:
# Count how many attendees of each bootcamp would recommend the bootcamp

RecYes = AttendedBootcamp_pd[ AttendedBootcamp_pd ["BootcampRecommend"] == "Yes"]


GroupRec = pd.DataFrame(RecYes.groupby(["BootcampName"]).count ()["BootcampRecommend"])


GroupRec = GroupRec.reset_index() 


GroupRec

                 BootcampName  BootcampRecommend
0                  10x.org.il                  3
1              4Geeks Academy                  4
2                    AcadGild                  2
3          Academia de Código                  4
4                         Ada                  8
5         AngelHack Education                  1
6    Anyone Can Learn To Code                  5
7                 App Academy                 20
8       Austin Coding Academy                  1
9              Base10 Academy                  1
10                   Betamore                  1
11             Big Nerd Ranch                  2
12               Bit Bootcamp                  2
13              Bitmaker Labs                  3
14                    Bloc.io                 11
15             BoiseCodeWorks                  2
16               BrainStation                  2
17               Byte Academy                  1
18        CODEcamp Charleston                  2
19             Camp Code Away                  2
20              CareerFoundry                  4
21              Claim Academy                  1
22                    Code 42                  1
23               Code Fellows                 15
24             Code Institute                  1
25               Code Platoon                  2
26                 Code Union                  1
27          CodeCore Bootcamp                  3
28           CodeCraft School                  1
29        CodeMasters Academy                  1
..                        ...                ...
86             PDX Code Guild                  1
87      Prime Digital Academy                 25
88                  RefactorU                  2
89          Ruby On The Beach                  1
90    Rutgers Coding Bootcamp                  3
91                   Sabio.la                  3
92    Science to Data Science                  1
93                  SeedPaths                  1
94                 Skillcrush                  3
95             Software Guild                  8
96                 Stackademy                  1
97             Starter League                  1
98          Startup Institute                  4
99      Tech Academy Portland                  2
100         Tech Talent South                  8
101         Telegraph Academy                  2
102        The Data Incubator                  1
103      The Firehose Project                 13
104             The Iron Yard                 31
105                  Thinkful                  5
106                    Turing                 26
107                  V School                  1
108        Viking Code School                 10
109            We Can Code IT                  1
110             We Got Coders                  2
111                   Wyncode                  3
112       Zip Code Wilmington                  1
113                     codeU                  1
114               devCodeCamp                  4
115                tradecraft                  1

[116 rows x 2 columns]

In [30]:
# Merge the two created data frames on the name of tbe bootcamp

Merge_Bootcampdata = pd.merge (number_of_participants_pd,GroupRec, on = "BootcampName" )

Merge_Bootcampdata.head()

            BootcampName  counts  BootcampRecommend
0       General Assembly      90                 70
1        Flatiron School      54                 50
2           Dev Bootcamp      48                 41
3          The Iron Yard      40                 31
4  Prime Digital Academy      30                 25

In [39]:
# Calculate percentage of each bootcamp's students who are recommenders
# Think of what should be the numerator and the demoninator


Merge_Bootcampdata["PercentRecom"] =Merge_Bootcampdata["BootcampRecommend"]/Merge_Bootcampdata["counts"]*100
Merge_Bootcampdata


# Sort results in descending order
# Format for percentages

Merge_Bootcampdata["PercentRecom"]  = Merge_Bootcampdata.sort_values("PercentRecom", ascending= False)["PercentRecom"].map("{0:,.2f}%".format)
Merge_Bootcampdata.sort_values("PercentRecom", ascending= False).head()

,BootcampName,counts,BootcampRecommend,PercentRecom
6,Turing,27,26,96.30%
16,Free Code Camp is not a bootcamp - please scro...,15,14,93.33%
5,Hack Reactor,29,27,93.10%
1,Flatiron School,54,50,92.59%
7,App Academy,22,20,90.91%

In [40]:
# Export to excel and remove index

Merge_Bootcampdata.to_excel("Output.xlsx")